### ISSUE TITLE
Huggingface online demo does not work

### ISSUE THREAD

**Issue by X1AOX1A** [vasudevgupta7/bigbird#11]
Hi there,

it seems like the huggingface online [demo](https://huggingface.co/spaces/vasudevgupta/BIGBIRD_NATURAL_QUESTIONS) does not work at the moment, even with the default example, could u help to fix it?

thanks

**Comment by thevasudevgupta** [comment]
working now: https://huggingface.co/spaces/vasudevgupta/BIGBIRD_NATURAL_QUESTIONS
