### ISSUE TITLE
Can I use roberta-base checkpoint for this?

### ISSUE THREAD

**Issue by heraclex12** [vasudevgupta7/bigbird#3]
Hi Gupta,

Thank you for your hard work. 
I want to use Bigbird for my own dataset in another language. But `google/bigbird-roberta-base` checkpoint was trained in English language. So can I load another checkpoint (for example `roberta-base`) to your model?

**Comment by thevasudevgupta** [comment]
You can initialize bigbird model from Roberta-checkpoint & train it in a BigBird fashion with block sparse attention. But remember RoBERTa checkpoint has seen seqlen upto 512 only & BigBird expects seqlen > 1024 atleast for good performance at reasonable compute.

```python
from transformers import BigBirdForQuestionAnswering

model = BigBirdForQuestionAnswering.from_pretrained("google/bigbird-roberta-base")
# Note that some of the weights are not used while initialising (mostly pooler layer)
# so you are good to go, but do check the warning carefully 
```

**Comment by heraclex12** [comment]
Gotcha. Thank you for your help.
