### ISSUE TITLE
BigBirdForNaturalQuestions

### ISSUE THREAD

**Issue by kishore-25** [vasudevgupta7/bigbird#5]
Hi Vasudevgupta,

I am interested in predicting category (long, short) answers, but as per your suggestion from the hugging face website (https://huggingface.co/vasudevgupta/bigbird-roberta-natural-questions), I am trying to use **BigBirdForNaturalQuestions**, but not able to find this class/model anywhere. Could you please help me on that where to get **BigBirdForNaturalQuestions** and how to get the long and short answers from that model?

Regards,
Kishore

**Comment by thevasudevgupta** [comment]
Here is the implementation: https://github.com/vasudevgupta7/bigbird/blob/ee33bf6ed5b12a16e41e363ae9c2aa776e1eb1a1/src/train_nq_torch.py#L64
