### ISSUE TITLE
BigBird Pegaus Training example

### ISSUE THREAD

**Issue by sorenmc** [vasudevgupta7/bigbird#7]
Hi @vasudevgupta7,

First of all nice job with merging BigBird to huggingface transformers! 
I wanted to try training my own BigBird Pegasus model, and I saw that you traiend multiple of these. Browsing both huggingface and your repositories, I did not meet an example of these, and wanted to ask if you have a simple example that you want to share that i can get started on?

**Comment by thevasudevgupta** [comment]
BigBird-pegasus training on summarization is very similar to pegasus training. I believe there would be tutorials for that in the HuggingFace repo. But I am not sure.
